### ISSUE TITLE
NPE in some converters when calculating updated attributes

### ISSUE THREAD

**Issue by TomTravaglino** [openhab/org.openhab.binding.zigbee#432] opened 2019-05-03 07:22 UTC
Caused by #427 and #409 

I'm experiencing a NPE in the method `ZigBeeConverterMeasurementPower.attributeUpdated(...)` thrown by this statement:
```
BigDecimal valueInWatt = BigDecimal.valueOf(value * multiplier / divisor);
```
The reason is that `multiplier` and `divisor` are both null. This happens because since #427 these variables are initialized in the method `initializeDevice()` which since #409 is only invoked on the very first initialization and then only `initializeConverter()` will be called on startup. Such variables should be better initialized in the method `initializeConverter()`.

Other converters which currently use to initialize variables in `initializeDevice()` will need to be changed too (didn't check them all).

**Comment by cdjackson** [comment] 2019-05-03 07:26
Please can you provide a PR for this?

**Comment by cdjackson** [comment] 2019-05-03 16:32
Duplicate of #430

**Closed** 2019-05-04 07:45 UTC
Labels: duplicate
